---
# task file for postgresql

- name: "Set the correct delegated_dbhost (to support postgres db deployment on a remote dbhost)"
  set_fact:
    delegated_dbhost: "{{ delegated_dbhost | default (zabbix_server_dbhost if (zabbix_server_dbhost != 'localhost') else inventory_hostname) }}"

- name: "PostgreSQL | Delegated"
  block:
    - name: "PostgreSQL | Delegated | Create | Database"
      postgresql_db:
        name: "{{ zabbix_server_dbname }}"
        port: "{{ zabbix_server_dbport }}"
        state: present

    - name: PostgreSQL | Delegated | Extension | Create
      postgresql_ext:
        name: timescaledb
        db: "{{ zabbix_server_dbname }}"
      when: zabbix_timescaledb

    - name: "PostgreSQL | Delegated | Create | User"
      postgresql_user:
        db: "{{ zabbix_server_dbname }}"
        name: "{{ zabbix_server_dbuser }}"
        password: "{{ zabbix_server_dbpassword }}"
        port: "{{ zabbix_server_dbport }}"
        priv: ALL
        state: present
        encrypted: yes
  become: yes
  become_user: postgres
  delegate_to: "{{ delegated_dbhost }}"
  when:
    - zabbix_database_creation
    - zabbix_server_pgsql_login_host is not defined
  tags:
    - zabbix-server
    - database

- name: "PostgreSQL | Remote"
  block:
    - name: "PostgreSQL | Remote | Create | Database"
      postgresql_db:
        login_host: "{{ zabbix_server_pgsql_login_host | default(omit) }}"
        login_user: "{{ zabbix_server_pgsql_login_user | default(omit) }}"
        login_password: "{{ zabbix_server_pgsql_login_password | default(omit) }}"
        login_unix_socket: "{{ zabbix_server_pgsql_login_unix_socket | default(omit) }}"
        name: "{{ zabbix_server_dbname }}"
        port: "{{ zabbix_server_dbport }}"
        state: present

    - name: "PostgreSQL | Remote | Create | User"
      postgresql_user:
        login_host: "{{ zabbix_server_pgsql_login_host | default(omit) }}"
        login_user: "{{ zabbix_server_pgsql_login_user | default(omit) }}"
        login_password: "{{ zabbix_server_pgsql_login_password | default(omit) }}"
        db: "{{ zabbix_server_dbname }}"
        name: "{{ zabbix_server_dbuser }}"
        password: "md5{{ (zabbix_server_dbpassword + zabbix_server_dbuser)|hash('md5') }}"
        port: "{{ zabbix_server_dbport }}"
        priv: ALL
        state: present
        encrypted: yes
  when:
    - zabbix_database_creation
    - zabbix_server_pgsql_login_host is defined
  tags:
    - zabbix-server
    - database

- name: "PostgreSQL | Create | Schema"
  shell: >
    cd {{ datafiles_path }} &&
    if [ -f create.sql.gz ]; then gunzip create.sql.gz ; fi &&
    psql -h '{{ zabbix_server_dbhost }}'
    -U '{{ zabbix_server_dbuser }}'
    -d '{{ zabbix_server_dbname }}'
    -p '{{ zabbix_server_dbport }}'
    -f create.sql && touch /etc/zabbix/schema.done
  args:
    creates: /etc/zabbix/schema.done
    warn: no
  environment:
    PGPASSWORD: '{{ zabbix_server_dbpassword }}'
  when:
    - zabbix_version is version('3.0', '>=')
    - zabbix_database_sqlload
  tags:
    - zabbix-server
    - database

- name: "Timescaledb | Convert | Schema"
  shell: >
    cd {{ datafiles_path }} &&
    if [ -f timescaledb.sql.gz ]; then gunzip timescaledb.sql.gz ; fi &&
    psql -h '{{ zabbix_server_dbhost }}'
    -U '{{ zabbix_server_dbuser }}'
    -d '{{ zabbix_server_dbname }}'
    -p '{{ zabbix_server_dbport }}'
    -f timescaledb.sql && touch /etc/zabbix/timescaledb.done
  args:
    creates: /etc/zabbix/timescaledb.done
    warn: no
  environment:
    PGPASSWORD: '{{ zabbix_server_dbpassword }}'
  when:
    - zabbix_database_sqlload
    - zabbix_timescaledb
  tags:
    - zabbix-server
    - database



